---
title: "in-class-code"
format: pdf
---

# Packages

```{r}
#| label: load-packages

# general use
library(tidyverse)

# file organization
library(here)

# data visualization
library(naniar)
library(patchwork)
```

# Data

```{r}
#| label: load-data
veg <- read_csv(here("data", "veg.csv"))

metadata <- read_csv(here("data", "vp_veg_metadata.csv"))
```

# Class code

```{r}
#| label: implicit-data
# create a new object from veg
gl_implicitNA <- veg |> 
  # filter all occurrences where transect_name contains GL
  filter(str_detect(transect_name, "GL") &
           site == "ncos") |> 
  # group by year, pool, and species
  group_by(year, transect_name, psoc) |>
  # calculate mean percent cover
  summarize(mean_pc = mean(percent_cover, na.rm = TRUE)) |> 
  # ungroup data frame
  ungroup() |> 
  # create a new column called year_pool from year and transect name
  unite("year_pool", year, transect_name, remove = TRUE) |>
  # join with metadata by year_pool
  left_join(metadata, by = "year_pool")
```

```{r}
#| label: explicit-data

# creating new object from veg
gl_explicit0 <- veg |> 
  # filter all occurrences where transect_name contains GL
  filter(str_detect(transect_name, "GL") &
           site == "ncos") |> 
  # complete all possible combinations of year, pool, psoc and distance
  complete(year, transect_name, psoc, transect_distance,
           # fill values of percent cover with 0
           fill = list(percent_cover = 0)
           ) |>
  # group by year, pool, and psoc
  group_by(year, transect_name, psoc) |>
  # calculate total percent cover across all quads
  summarize(sum_pc = sum(percent_cover, na.rm = TRUE)) |>
  # ungroup the data frame
  ungroup() |>
  # create a new column called year_pool from year and transect name
  unite("year_pool", year, transect_name, remove = TRUE) |> 
  # join with metadata data frame
  left_join(metadata, by = "year_pool") |> 
  # calculate mean percent cover from total percent cover/number of quadrats
  mutate(mean_pc = sum_pc/num_quad)
```

```{r}
#| label: native-species-explicit%cover

# creating new object from veg
gl_native_explicit0 <- veg |> 
  # filter all occurrences where transect_name contains GL & native
  filter(str_detect(transect_name, "GL") &
           site == "ncos" &
           cover_category == "NATIVE COVER") |> 
  # complete all possible combinations of year, pool, psoc and distance
  complete(year, transect_name, psoc, transect_distance,
           # fill values of percent cover with 0
           fill = list(percent_cover = 0)
           ) |>
  # group by year, pool, and psoc
  group_by(year, transect_name, psoc) |>
  # calculate total percent cover across all quads
  summarize(sum_pc = sum(percent_cover, na.rm = TRUE)) |>
  # ungroup the data frame
  ungroup() |>
  # create a new column called year_pool from year and transect name
  unite("year_pool", year, transect_name, remove = TRUE) |> 
  # join with metadata data frame
  left_join(metadata, by = "year_pool") |> 
  # calculate mean percent cover from total percent cover/number of quadrats
  mutate(mean_pc = sum_pc/num_quad)
```

```{r}
#| label: invasive-species-explicit%cover

# creating new object from veg
gl_invasive_explicit0 <- veg |> 
  # filter all occurrences where transect_name contains GL & native
  filter(str_detect(transect_name, "GL") &
           site == "ncos" &
           cover_category == "NON-NATIVE COVER") |> 
  # complete all possible combinations of year, pool, psoc and distance
  complete(year, transect_name, psoc, transect_distance,
           # fill values of percent cover with 0
           fill = list(percent_cover = 0)
           ) |>
  # group by year, pool, and psoc
  group_by(year, transect_name, psoc) |>
  # calculate total percent cover across all quads
  summarize(sum_pc = sum(percent_cover, na.rm = TRUE)) |>
  # ungroup the data frame
  ungroup() |>
  # create a new column called year_pool from year and transect name
  unite("year_pool", year, transect_name, remove = TRUE) |> 
  # join with metadata data frame
  left_join(metadata, by = "year_pool") |> 
  # calculate mean percent cover from total percent cover/number of quadrats
  mutate(mean_pc = sum_pc/num_quad)
```

```{r}
#| label: missingness-plots

gg_miss_var(gl_implicitNA)

gg_miss_var(gl_explicit0)
```

No missing values in either data frame.

# Grasslands vectors

```{r}
#| label: native-vector

# creating new vector from veg
native_spp <- veg |> 
  # filter all occurrences where transect_name contains GL
  filter(str_detect(transect_name, "GL") &
           site == "ncos" &
           cover_category == "NATIVE COVER") |> 
# pull to extract data frame column as a vector
  pull(psoc)

# sample of ten rows
sample(native_spp, 10)
```

```{r}
#| label: invasive-vector

# creating new vector from veg
invasive_spp <- veg |> 
  # filter all occurrences where transect_name contains GL and cover category is non-native
  filter(str_detect(transect_name, "GL") &
           site == "ncos" &
           cover_category == "NON-NATIVE COVER") |> 
# pull to extract data frame column as a vector
  pull(psoc)

# sample of ten rows
sample(invasive_spp, 10)
```

# Species richness

```{r}
#| label: native-richness

# create new object from gl_explicit0
native_species_rich <- gl_explicit0 |> 
# group by year and pool
  group_by(year, transect_name) |> 
# filter data frame with vector into get native species, 
# also filter percent cover to identify species presence
  filter(psoc %in% native_spp, mean_pc > 0) |> 
# species richness calculation
  summarize(spp_rich = n_distinct(psoc)) |> 
  # ungroup data frame
  ungroup()

# sample 10 rows
slice_sample(native_species_rich, n = 10)
```

```{r}
#| label: non-native-richness

# create new object from gl_explicit0
invasive_species_rich <- gl_explicit0 |> 
# group by year and pool
  group_by(year, transect_name) |> 
# filter data frame with vector into get native species, 
# also filter percent cover to identify species presence
  filter(psoc %in% invasive_spp, mean_pc > 0) |> 
# species richness calculation
  summarize(spp_rich = n_distinct(psoc)) |> 
  # ungroup data frame
  ungroup()

# sample 10 rows
slice_sample(invasive_species_rich, n = 10)
```

# Outliers???

```{r}

```

# Total Cover

```{r}
#| label: total-cover-native-veg

# create new object from veg
native_pc <- veg |>
  # filter only native species
  filter(psoc %in% native_spp) |>
  # filter only grasslands at NCOS
  filter(str_detect(transect_name, "GL") & site == "ncos") |>
  # group by year and transect
  group_by(year, transect_name) |> 
  # calculate implicit missingness sum
  summarize(sum_pc = sum(percent_cover, na.rm = TRUE)) |> 
  # ungroup data frame
  ungroup() |> 
  # united column to match the one in metadata
  unite("year_pool", year, transect_name, remove = TRUE) |>
  # join metadata
  left_join(metadata, by = "year_pool") |> 
  # dividing total % cover by the # of quadrats in the observed year
  mutate(total_pc = sum_pc/num_quad)
  
  # sample of 10
slice_sample(native_pc, n = 10)
```

```{r}
#| label: total-cover-non-native-veg

# create new object from veg
invasive_pc <- veg |>
  # filter only invasive species
  filter(psoc %in% invasive_spp) |>
  # filter only grasslands at NCOS
  filter(str_detect(transect_name, "GL") & site == "ncos") |>
  # group by year and transect
  group_by(year, transect_name) |> 
  # calculate implicit missingness sum
  summarize(sum_pc = sum(percent_cover, na.rm = TRUE)) |> 
  # ungroup data frame
  ungroup() |> 
  # united column to match the one in metadata
  unite("year_pool", year, transect_name, remove = TRUE) |>
  # join metadata
  left_join(metadata, by = "year_pool") |> 
  # dividing total % cover by the # of quadrats in the observed year
  mutate(total_pc = sum_pc/num_quad)
  
  # sample of 10
slice_sample(invasive_pc, n = 10)
```


# Interest species wrangling

```{r}
#| label: native and non native species list


# native species
# species most significant: Stipa_pulchra and Distichlis_spicata
native_interest <- c(
  "Stipa_pulchra",
  "Distichlis_spicata",
  "Deinandra_fasciculata",
  "Erigeron_canadensis",
  "Symphyotrichum_subulatum"
)

# invasive / non-native species
# species most significant: Festuca_perennis and Polypogon_monspeliensis
non_native_interest <- c(
  "Festuca_perennis",
  "Polypogon_monspeliensis",
  "Bromus_hordeaceus",
  "Festuca_myuros",
  "Medicago_polymorpha"
)

# all selected species
all_interest <- c(
  "Stipa_pulchra",
  "Distichlis_spicata",
  "Deinandra_fasciculata",
  "Erigeron_canadensis",
  "Symphyotrichum_subulatum",
  "Festuca_perennis",
  "Polypogon_monspeliensis",
  "Bromus_hordeaceus",
  "Festuca_myuros",
  "Medicago_polymorpha"
)
```

```{r}
#| label: filtering-interest-species

gl_native_interest <- gl_native_explicit0 |> 
  filter(psoc %in% native_interest) |> 
  mutate(native = "native")

gl_invasive_interest <- gl_invasive_explicit0 |> 
  filter(psoc %in% non_native_interest) |> 
  mutate(native = "non_native")

gl_all_interest <- bind_rows(gl_native_interest, gl_invasive_interest)
```


```{r}
#| label: wrangling-vis-1
# data frame for vis 1
gl_all_pc <- gl_all_interest  |> 
  group_by(psoc, year, native) |> 
  summarize(sum_pc = sum(sum_pc),
            sum_quad = sum(num_quad)) |> 
  ungroup() |> 
  mutate(mean_pc = sum_pc/sum_quad)
```

```{r}
#| label: wrangling-vis-2
# tbd

```


```{r}
#| label: wrangling-vis-3
# data frames for vis 3
gl_native_tc <- gl_native_interest |> 
  group_by(psoc, year_pool, native) |> 
  summarize(sum_pc = sum(sum_pc)) |> 
  ungroup()

gl_invasive_tc <- gl_invasive_interest |> 
  group_by(psoc, year_pool, native) |> 
  summarize(sum_pc = sum(sum_pc)) |> 
  ungroup()
```

```{r}
#| label: wrangling-vis-4
gl_stacked_native <- gl_all_interest |> 
  group_by(native, year) |> 
  summarize(mean_pc_sum = sum(mean_pc)) |> 
  ungroup() |> 
  mutate(native)

```


# Visualizations

```{r}
#| label: vis-1
vis1 <- ggplot(data = gl_all_pc,
       aes(x = year,
           y = mean_pc,
           color = psoc)) +
  geom_line() +
  facet_wrap(~ native)

vis1
```

```{r}
#| label: vis-3

native_tc_plot <- ggplot(data = gl_native_tc,
       aes(x = psoc,
           y = sum_pc,
           color = psoc)) +
  geom_jitter(height = 0,
              width = 0.2) +
  stat_summary(geom = "pointrange",
               # argument to calculate standard error
               fun.data = mean_sdl,
               fun.args = list(mult = 1),
               size = 1,
               linewidth = 1,
               color = "red") +  
  labs(title = "Native Total Cover") +
  theme(legend.position = "none")

invasive_tc_plot <- ggplot(data = gl_invasive_tc,
       aes(x = psoc,
           y = sum_pc,
           color = psoc)) +
  geom_jitter(height = 0,
              width = 0.2) +
  stat_summary(geom = "pointrange",
               # argument to calculate standard error
               fun.data = mean_sdl,
               fun.args = list(mult = 1),
               size = 1,
               linewidth = 1,
               color = "red") +  
  labs(title = "Non-native Total Cover") +
  theme(legend.position = "none")

vis3 <- native_tc_plot + invasive_tc_plot
vis3
```

```{r}
#| label: vis-4

vis4 <- ggplot(data = gl_stacked_native,
               aes(x = year,
                   y = mean_pc_sum,
                   fill = native)) +
  geom_area()

vis4
```

