---
title: "Timeline check-in"
author: "Alyssa Hagele, Abby Malech, Henderson Vo"
date: 2026-05-22
format: pdf
---

# Ideas for analysis and background

## Background analysis

For our background, we want to look at the history of the open space and how this might have contributed to a need for native restoration as well as invasive species removal. This will relate to our research question of **"how has percent cover of key native species and overall native species richness changed through time in grasslands compared to non native species?"** as historical context will further guide our understanding of change in grassland species composition since the restoration project began. 

In addition to our primary research question, secondary questions we have on vegetation include:
- How have key species changed through time in major habitats?
- How does native grassland abundance compare to non-native abundance over time?
- Which transects might show more or less abundance in native grassland vegetation over time?

## Data analysis

Our questions 
, the CCBER native plant catalog (found [here](https://www.ncos.ccber.ucsb.edu/native-plant-habitats)),

## Literature review

Besides analyzing our data, we will need literary resources to inform the nature of these questions and why these changes over time are important to wetland habitat's and the overall California landscape. Our literature review will include a mix of peer reviewed journals as well as the 2024 monitoring report.These resources may help us to get a more holistic understanding of the grassland habitat at NCOS because restoration efforts are one of the primary drivers of change in native species cover and richness.

# Visualizations 

## figures directly relevant to answering questions

## Other exploratory visualizations

## should include visualization made in class last week and will make this week

# Plan for elective

- Final product: trifold brochure made on canva showing: (5) native species of focus in the grassland habitat + two non native species + restoration techniques + history of NCOS
- Would possibly replace online images of plant species with our own if we have the time to go to NCOS and I.D. plants
- Please see our rough draft for the elective brochure in the README:

**Plan**

- Week 8 → finish gathering information on key species + 2 non native key species 
- Week 9 → finish trifold design 
- Week 10 → possibly present *or* finalize details to present during finals week
